"""C13: LaTeX macros for the numbers added on 7 October 2026 (prefix \\ck, file tables/ck_extra.tex).

Reads results/c1_verify.json (one-item power), c11_bundle_anchor.json (Type-I of the uncalibrated bundle
test with estimated abilities), c11b_bundle_regression_null.json and c12_matched_humans.json.
Rounding is half up, as in c6_tables.py.
"""
import os, json, math
from decimal import Decimal, ROUND_HALF_UP

HERE = os.path.dirname(__file__)
RES = os.path.join(HERE, "results")
J = lambda f: json.load(open(os.path.join(RES, f)))


def r(x, nd=2):
    q = Decimal(1).scaleb(-nd)
    return str(Decimal(repr(float(x))).quantize(q, rounding=ROUND_HALF_UP))


def pv(x, n):
    """p = (1 + k)/(n + 1); at the floor, print the bound."""
    return r(x, 3) if x > 1.5 / (n + 1) else r(1 / (n + 1), 3)


M = {}
c1 = J("c1_verify.json")["power_one_item"]
M["ckPowItemOne"] = r(c1["1.0_easier"]["median"])
M["ckPowItemTwo"] = r(c1["2.0_easier"]["median"])
M["ckPowItemThree"] = r(c1["3.0_easier"]["median"])

c11 = J("c11_bundle_anchor.json")["main"]["VR16"]["letter_mean"]["calibrated"]
t1 = {k: v["typeI_005"] for k, v in c11.items()}
M["ckBxTypeIMax"] = r(max(t1.values()))
M["ckBxTypeIFixedOneD"] = r(t1["1D_fixed"])
M["ckBxTypeIMatchedTwoD"] = r(t1["2D_matched"])

c11b = J("c11b_bundle_regression_null.json")
n = c11b["nrep"]
M["ckBxRegTwoMatched"] = r(c11b["null"]["matched"]["p_two_sided"])
M["ckBxRegTwoFixed"] = r(c11b["null"]["fixed"]["p_two_sided"])
M["ckBxRegOneMatched"] = f"{max(0.001, math.ceil(c11b['null']['matched']['p_one_sided_deficit'] * 1000) / 1000):.3f}"   # used as p <= x
M["ckBxRegReps"] = f"{n:,}".replace(",", "{,}")

c12 = J("c12_matched_humans.json")
n12 = c12["nrep"]
g5, g8 = c12["matched"]["ge5_other"], c12["matched"]["ge8_other"]
M["ckHumThetaUnmatched"] = ("+" if c12["unmatched_pool_mean_theta"] >= 0 else "$-$") + r(abs(c12["unmatched_pool_mean_theta"]))
M["ckMatchTheta"] = "$-$" + r(abs(g5["theta_matched_group_mean"]))
M["ckMatchCaliper"] = r(g5["caliper"])
M["ckMatchPbMean"] = r(g5["exact_pb"]["mean"], 3)
M["ckMatchPbMax"] = r(g5["exact_pb"]["max"])
M["ckMatchSlMean"] = r(g5["stoploss"]["mean"], 3)
M["ckMatchPModal"] = pv(g5["exact_pb"]["p_modal_020"], n12)
M["ckMatchPSingle"] = pv(g5["exact_pb"]["p_single_012"], n12)
M["ckMatchPRunMean"] = pv(g5["stoploss"]["p_runmean_008"], n12)
M["ckMatchEightPSingle"] = pv(g8["exact_pb"]["p_single_012"], n12)
M["ckMatchEightPRunMean"] = pv(g8["stoploss"]["p_runmean_008"], n12)

os.makedirs(os.path.join(HERE, "tables"), exist_ok=True)
with open(os.path.join(HERE, "tables", "ck_extra.tex"), "w") as f:
    f.write("% generated by camera_ready_checks/c13_macros.py -- do not edit by hand\n")
    for k, v in M.items():
        f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
for k, v in M.items():
    print(f"{k:24s} {v}")
